---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: ubuntu
    tag: jammy

inputs:
- name: bbl-cli-dev
- name: bosh-bootloader
- name: dockerfiles

outputs:
- name: docker-workspace

params:
  DOCKERFILE:

run:
  path: /bin/bash
  args:
  - -c
  - |
    cp -R ./bosh-bootloader docker-workspace/
    cp "./dockerfiles/${DOCKERFILE}" docker-workspace/
    cp ./bbl-cli-dev/bin/bbl-*linux_amd64 docker-workspace/bbl
